<?php
class dbMigrate extends HelperClass
{
	// Databse HOST
	protected static $db_host;
	protected static $db_name;
	protected static $db_pass;
	protected static $db_user;
	// Do not add a value! will be altered by the database configuation file!!!!

	public static function config($default, $config_array)
	{
		// loop
		$current_config = [];

		if(!empty($default))
		{
			foreach($config_array as $db_type => $config)
			{
				if(substr_count($db_type, $default))
				{
					// found!
					$current_config = $config;
				}
			}

			if(count($current_config) > 0)
			{
				$ca = $current_config;
				self::$db_host = isset($ca['db_host']) ? $ca['db_host'] : "";
				self::$db_name = isset($ca['db_name']) ? $ca['db_name'] : "";
				self::$db_pass = isset($ca['db_pass']) ? $ca['db_pass'] : "";
				self::$db_user = isset($ca['db_user']) ? $ca['db_user'] : "";
			}

			self::use_connection($default);	
		}
		else
		{
			// delete any active connection
			$location = "app/helpers/db.php";
			if(file_exists($location))
			{
				unlink("app/helpers/db.php");	
			}
		}

	}


	// Configuration set, lets use a connection
	public static function use_connection($name)
	{
		// check if file can be found
		$location = "db/database/{$name}.php";
		if(!file_exists($location))
		{
			$fh = fopen($location, "w+");
			$name = ucfirst($name);
			$class_name = "DB_{$name}";
			$write = "
<?php

// We include our DB Migration file 
include_once('db/dbMigrate.php');

// Including DB Migration file and Extending it gives us access to
// db_user, db_name, db_host and db_pass
// So you can create your connection method how you see fit.

class {$class_name} extends dbMigrate
{
	// Created by XchrisCode
	// You can continue from here
	private static function connect()
	{
		// Go On please!
	}
}";
			fwrite($fh, $write);
			fclose($fh);

			// check if we have db.php in helper folder
			$location = "app/helpers/db.php";
			if(file_exists($location))
			{
				// we have to delete it
				unlink($location);
			}
			else
			{
				// ok we would create a new file and include our new database class
				$fh = fopen($location, "w+");
				$lower = strtolower($name);
				$write = "
<?php
// Generated by XchrisCode
// {$name} Database file
include_once('./db/database/{$lower}.php');

// DB class here
class db extends {$class_name}
{

}				
				";
				fwrite($fh, $write);
				fclose($fh);
			}
		}
		else
		{
			if($name != "")
			{
				$name = ucfirst($name);
				$class_name = "DB_{$name}";

				// check if we have db.php in helper folder
				$location = "app/helpers/db.php";
				if(file_exists($location))
				{
					// we have to delete it
					unlink($location);
				}
				else
				{
					// ok we would create a new file and include our new database class
					$fh = fopen($location, "w+");
					$lower = strtolower($name);
					$write = "
	<?php
	// Generated by XchrisCode
	// {$name} Database file
	include_once('./db/database/{$lower}.php');

	// DB class here
	class db extends {$class_name}
	{

	}				
					";
					fwrite($fh, $write);
					fclose($fh);
				}
			}
		}
		
	}
}